#include <iostream>
#include <fstream>
#include <string>

using namespace std;
// 4. Write Program 2 (readData.cpp) which will read  the data from the file generated by generateData.cpp into a two dimensional array (125 rows by 20 columns) - do not include the sum-column, BUT you must check that the row read sums up to the value in the sum-column.  If it does not, you should report an error.  AFTER you have the data in the 2-D array, use the functions you created in steps 1, 2, and 3 to find the maximum value in the array and the minimum value in the array.  Report these values in main, not in the function. Use the functions you created in steps 1, 2, and 3 to count the number of "0"s that are in the file. Report that value in main, not in the function. Create a function that prints the entire array to the terminal.  Use the function to print the array.

void readData(const string& filename, int data[125][20], int rows, int cols) {
    ifstream file(filename);
    if (file.is_open()) {
        for (int i = 0; i < rows; ++i) {
            int sum = 0;
            for (int j = 0; j < cols; ++j) {
                file >> data[i][j];
                sum += data[i][j];
            }
            int fileSum;
            file >> fileSum;
            if (sum != fileSum){
                cerr << "Error: Sum mismatched in row" << i + 1 << endl;
            }
        }
        file.close(); // Close the file after reading
    } else {
        cerr << "Error: Unable to open file " << filename << endl;
    }
}

// Function to print a 2D array
void print2DArray(int data[125][20], int rows, int cols) {
    for (int i = 0; i < rows; ++i) {
        for (int j = 0; j < cols; ++j) {
            cout << data[i][j] << " ";
        }
        cout << endl;
    }
}

int main() {
    const int ROWS = 125;
    const int COLS = 20;

    int data[ROWS][COLS];

    readData("julian.txt", data, ROWS, COLS);
    print2DArray(data, ROWS, COLS);

    return 0;
}